### ISSUE TITLE
The requested platform 'PingHosts' was not registered by any plugin

### ISSUE THREAD

**Issue by Traktuner** [vectronic/homebridge-ping-hosts#1]
Hello,
I edited the package.json and added the sample code in config.json which is provided in the readme.
But when I start homebridge, i get the following error: 
Error: The requested platform 'PingHosts' was not registered by any plugin.
Any idea what I can do?
Thank you

**Comment by vectronic** [comment]
To clarify: you need to be adding the following (example) snippet into the `platforms` sections of your homebridge installation's `config.json`:

```
{
  "platform": "PingHosts",
  "hosts": [
    {
      "name": "Internet",
      "host": "8.8.8.8",
      "interval": 120,
      "timeout": 25,
      "retries": 3
    }
  ]
},
```

In your issue description you said you had added this to the `package.json` file which is not correct!

**Comment by Traktuner** [comment]
Hello,
sorry for the confusion. Yes, that is exactly what I did. (PingHosts ist the only section in "platforms []"
in the package.json file I only added the dependency as described in your example ("net-ping": "^1.2.1")
This is the full error text:
Attached you can find the full error text:
<img width="797" alt="Bildschirmfoto 2020-01-06 um 00 39 43" src="https://user-images.githubusercontent.com/8493491/71787933-c4133780-301d-11ea-8280-f7b20fd63aa6.png">

**Comment by vectronic** [comment]
I have updated the readme with the correct instructions for installing this fork as I realise if you follow what was there, it would have installed the upstream original code from the npm registry.

Make you you uninstall the upstream npm package first however e.g. `npm uninstall -g homebridge-ping-hosts`

Then do (as the readme now says):

`npm install -g git://github.com/vectronic/homebridge-ping-hosts.git --unsafe-perm`

If you install my fork of this plugin using the above command you shouldn't need to be editing any `package.json` file.

If you still have trouble, send me the full homebridge logs (in my experience if you get an 'unregistered platform' error it is because earlier in the logs there is a NodeJS exception relating to the plugin module not loading correctly).

**Comment by Traktuner** [comment]
Thank you very much for your help! Now it works as it should :-)
