### ISSUE TITLE
Default showing Open

### ISSUE THREAD

**Issue by whreams** [vectronic/homebridge-ping-hosts#11]
Just upgraded to new release.
No change to config, however default now shows to be open upon successful ping.  Config follows...

   "name": "Network Grid",
                    "host": "172.217.6.142",
                    "interval": 30,
                    "timeout": 25,
                    "retries": 1

**Comment by vectronic** [comment]
Yeah sorry for that, I see there was a bug now in the PR I merged.

Anyway, you prompted me to look more at the code and I've introduced 2 new config properties:

"startup_as_failed": defaults to true
"closed_on_success": defaults to true

https://www.npmjs.com/package/@vectronic/homebridge-ping-hosts

I've bumped the version to "2.0.0" to reflect the config has changed somewhat. I am so lost in Boolean logic right now but I think if you upgrade to this, you should get your old expected behaviour back, without having to change config...

**Comment by whreams** [comment]
All good.  Thanks for the work on this.

**Comment by whreams** [comment]
Now running 2.0.  Working as expected.  I consider closed unless you or others have different expectations.  Thanks!
